[project]
name = "littlex2"
version = "0.1.0"
description = "A Jac project"
entry-point = "main.jac"

[dependencies]

[dev-dependencies]
watchdog = ">=3.0.0"

[plugins.scale.database]
mongodb_uri = ""    # Auto-provisioned in K8s
redis_url = "redis://localhost:6379"      # Auto-provisioned in K8s
shelf_db_path = ".jac/data/anchor_store.db"